//! Build script: embeds the Windows icon and version resource.
//!
//! The resource script is generated rather than committed so the version, the
//! publisher and the copyright come from `Cargo.toml` and `src/lib.rs` alone.
//! A hand-maintained `.rc` would be a second place to bump on every release,
//! and the one that gets forgotten — leaving the shipped binary claiming an old
//! version in its file properties.

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(windows)]
    windows::embed_resources();
}

#[cfg(windows)]
mod windows {
    use std::path::{Path, PathBuf};

    pub fn embed_resources() {
        println!("cargo:rerun-if-changed=logo.ico");

        let manifest_dir = PathBuf::from(
            std::env::var("CARGO_MANIFEST_DIR")
                .expect("CARGO_MANIFEST_DIR is always set by cargo"),
        );
        let out_dir = PathBuf::from(
            std::env::var("OUT_DIR").expect("OUT_DIR is always set by cargo"),
        );

        let icon = manifest_dir.join("logo.ico");
        assert!(icon.is_file(), "logo.ico is missing at {}", icon.display());

        let script = out_dir.join("mcopy.rc");
        // A UTF-8 BOM is required, not cosmetic: both Microsoft's rc.exe and
        // llvm-rc otherwise decode the script in the system ANSI codepage, and
        // the non-ASCII letters in the copyright holder's name come out as
        // mojibake in the shipped binary's file properties.
        let mut source = String::from('\u{feff}');
        source.push_str(&resource_script(&icon));
        std::fs::write(&script, source)
            .expect("could not write the generated resource script");

        embed_resource::compile(&script, embed_resource::NONE);

        // Expose what actually went into the binary so a unit test can assert
        // it matches `APP_PUBLISHER` / `APP_COPYRIGHT`. Without this the two
        // copies could drift silently and the shipped .exe would disagree with
        // every other packaging artifact.
        println!("cargo:rustc-env=MCOPY_RESOURCE_PUBLISHER={PUBLISHER}");
        println!("cargo:rustc-env=MCOPY_RESOURCE_COPYRIGHT={COPYRIGHT}");
    }

    fn resource_script(icon: &Path) -> String {
        let version = std::env::var("CARGO_PKG_VERSION")
            .expect("CARGO_PKG_VERSION is always set by cargo");
        let description = std::env::var("CARGO_PKG_DESCRIPTION")
            .unwrap_or_else(|_| "mcopy".to_string());

        // VERSIONINFO wants four numeric fields; semver gives us three.
        let numeric = numeric_version(&version);

        format!(
            r#"// Generated by build.rs — do not edit.
#include <winver.h>

1 ICON "{icon}"

VS_VERSION_INFO VERSIONINFO
FILEVERSION     {numeric}
PRODUCTVERSION  {numeric}
FILEFLAGSMASK   VS_FFI_FILEFLAGSMASK
FILEFLAGS       0x0L
FILEOS          VOS_NT_WINDOWS32
FILETYPE        VFT_APP
FILESUBTYPE     VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        // 040904B0 = US English, Unicode.
        BLOCK "040904B0"
        BEGIN
            VALUE "CompanyName",      "{publisher}"
            VALUE "FileDescription",  "{description}"
            VALUE "FileVersion",      "{version}"
            VALUE "InternalName",     "mcopy"
            VALUE "LegalCopyright",   "{copyright}"
            VALUE "OriginalFilename", "mcopy.exe"
            VALUE "ProductName",      "mcopy"
            VALUE "ProductVersion",   "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#,
            icon = escape_rc_string(&icon.to_string_lossy()),
            numeric = numeric,
            version = version,
            description = escape_rc_string(&description),
            publisher = escape_rc_string(PUBLISHER),
            copyright = escape_rc_string(COPYRIGHT),
        )
    }

    /// Kept in step with `mcopy::APP_PUBLISHER` / `mcopy::APP_COPYRIGHT`.
    ///
    /// A build script cannot depend on the crate it is building, so these are
    /// duplicated here and pinned by a test in `src/lib.rs`.
    const PUBLISHER: &str = "NAKAMOZ";
    const COPYRIGHT: &str = "Copyright (c) 2026 Nevzat ÇELİKKANAT";

    /// `0.3.0` -> `0,3,0,0`, tolerating pre-release suffixes.
    fn numeric_version(version: &str) -> String {
        let core = version.split(['-', '+']).next().unwrap_or(version);

        let mut parts: Vec<u16> = core
            .split('.')
            .map(|part| part.parse().unwrap_or(0))
            .collect();
        parts.resize(4, 0);

        parts
            .iter()
            .map(u16::to_string)
            .collect::<Vec<_>>()
            .join(",")
    }

    /// Escape a value for a double-quoted RC string.
    ///
    /// Windows paths are full of backslashes and the resource compiler treats
    /// them as escapes, so an unescaped path silently corrupts the icon
    /// reference.
    fn escape_rc_string(value: &str) -> String {
        value.replace('\\', "\\\\").replace('"', "\\\"")
    }
}
